# Generated by Django 4.0.4 on 2022-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_lista_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='cor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cor em Hexadecimal'),
        ),
    ]
