# Generated by Django 4.0.4 on 2022-05-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_lista_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='cor',
        ),
        migrations.AddField(
            model_name='lista',
            name='corBg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cor Do Background em Hexadecimal'),
        ),
        migrations.AddField(
            model_name='lista',
            name='corTt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cor do Titulo em Hexadecimal'),
        ),
        migrations.AddField(
            model_name='lista',
            name='corTx',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cor dos textos em Hexadecimal'),
        ),
    ]
